//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompasDataContext : DbContext
    {
        public CompasDataContext()
            : base("name=CompasDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ContractorCard> ContractorCards { get; set; }
        public DbSet<Contractor> Contractors { get; set; }
        public DbSet<ContractorType> ContractorTypes { get; set; }
        public DbSet<Currency> Currencies { get; set; }
        public DbSet<CWCarBrand> CWCarBrands { get; set; }
        public DbSet<CWCarModel> CWCarModels { get; set; }
        public DbSet<CWCar> CWCars { get; set; }
        public DbSet<CWContractorCar> CWContractorCars { get; set; }
        public DbSet<Enterprise> Enterprises { get; set; }
        public DbSet<OrderState> OrderStates { get; set; }
        public DbSet<SecurityAction> SecurityActions { get; set; }
        public DbSet<SecurityCategory> SecurityCategories { get; set; }
        public DbSet<SecurityRoleAction> SecurityRoleActions { get; set; }
        public DbSet<SecurityRole> SecurityRoles { get; set; }
        public DbSet<SecurityUserRole> SecurityUserRoles { get; set; }
        public DbSet<SecurityUser> SecurityUsers { get; set; }
        public DbSet<StaffDepartmentEmployee> StaffDepartmentEmployees { get; set; }
        public DbSet<StaffDepartment> StaffDepartments { get; set; }
        public DbSet<StaffEmployee> StaffEmployees { get; set; }
        public DbSet<StaffEmployeeWorkPlace> StaffEmployeeWorkPlaces { get; set; }
        public DbSet<StaffSalary> StaffSalaries { get; set; }
        public DbSet<StaffSheduler> StaffShedulers { get; set; }
        public DbSet<StaffShedulerTeamEmployee> StaffShedulerTeamEmployees { get; set; }
        public DbSet<StaffShift> StaffShifts { get; set; }
        public DbSet<StaffTeamEmployee> StaffTeamEmployees { get; set; }
        public DbSet<StaffTeam> StaffTeams { get; set; }
        public DbSet<StaffWorkPlace> StaffWorkPlaces { get; set; }
        public DbSet<WareBas> WareBases { get; set; }
        public DbSet<WareCardBalace> WareCardBalaces { get; set; }
        public DbSet<WareCardBalanceOperation> WareCardBalanceOperations { get; set; }
        public DbSet<WareCardCar> WareCardCars { get; set; }
        public DbSet<WareCard> WareCards { get; set; }
        public DbSet<WareCardTypeDiscount> WareCardTypeDiscounts { get; set; }
        public DbSet<WareCardType> WareCardTypes { get; set; }
        public DbSet<WareCategory> WareCategories { get; set; }
        public DbSet<WareCode> WareCodes { get; set; }
        public DbSet<WareComponentDetail> WareComponentDetails { get; set; }
        public DbSet<WareComponentRelation> WareComponentRelations { get; set; }
        public DbSet<WareComponent> WareComponents { get; set; }
        public DbSet<WareDepartment> WareDepartments { get; set; }
        public DbSet<WareDiscountRule> WareDiscountRules { get; set; }
        public DbSet<WareDiscount> WareDiscounts { get; set; }
        public DbSet<WareDiscountType> WareDiscountTypes { get; set; }
        public DbSet<WareDocumentDetail> WareDocumentDetails { get; set; }
        public DbSet<WareDocument> WareDocuments { get; set; }
        public DbSet<WareDocumentStaffDetail> WareDocumentStaffDetails { get; set; }
        public DbSet<WareDocumentType> WareDocumentTypes { get; set; }
        public DbSet<WareExtra> WareExtras { get; set; }
        public DbSet<WareManufacturer> WareManufacturers { get; set; }
        public DbSet<WareOrderCar> WareOrderCars { get; set; }
        public DbSet<WareOrderDetail> WareOrderDetails { get; set; }
        public DbSet<WareOrder> WareOrders { get; set; }
        public DbSet<WareOrderState> WareOrderStates { get; set; }
        public DbSet<WarePriceGroup> WarePriceGroups { get; set; }
        public DbSet<WarePrice> WarePrices { get; set; }
        public DbSet<Ware> Wares { get; set; }
        public DbSet<WareUnit> WareUnits { get; set; }
    }
}
