//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contractor
    {
        public Contractor()
        {
            this.ContractorCards = new HashSet<ContractorCard>();
            this.CWContractorCars = new HashSet<CWContractorCar>();
            this.WareDocuments = new HashSet<WareDocument>();
        }
    
        public int ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public bool Client { get; set; }
        public bool Provider { get; set; }
        public bool Employee { get; set; }
        public int ContractorTypeID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string Phone { get; set; }
        public string MobilePhone { get; set; }
        public string EMail { get; set; }
        public string Site { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<bool> Sex { get; set; }
    
        public virtual ICollection<ContractorCard> ContractorCards { get; set; }
        public virtual ContractorType ContractorType { get; set; }
        public virtual ICollection<CWContractorCar> CWContractorCars { get; set; }
        public virtual ICollection<WareDocument> WareDocuments { get; set; }
    }
}
