//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CWCarBrand
    {
        public CWCarBrand()
        {
            this.CWCarModels = new HashSet<CWCarModel>();
            this.CWCars = new HashSet<CWCar>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<CWCarModel> CWCarModels { get; set; }
        public virtual ICollection<CWCar> CWCars { get; set; }
    }
}
