//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CWCarModel
    {
        public CWCarModel()
        {
            this.CWCars = new HashSet<CWCar>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int BrandID { get; set; }
    
        public virtual CWCarBrand CWCarBrand { get; set; }
        public virtual ICollection<CWCar> CWCars { get; set; }
    }
}
