//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CWCar
    {
        public CWCar()
        {
            this.CWContractorCars = new HashSet<CWContractorCar>();
            this.WareCardCars = new HashSet<WareCardCar>();
            this.WareOrderCars = new HashSet<WareOrderCar>();
        }
    
        public int ID { get; set; }
        public string Number { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<int> ModelID { get; set; }
    
        public virtual CWCarBrand CWCarBrand { get; set; }
        public virtual CWCarModel CWCarModel { get; set; }
        public virtual ICollection<CWContractorCar> CWContractorCars { get; set; }
        public virtual ICollection<WareCardCar> WareCardCars { get; set; }
        public virtual ICollection<WareOrderCar> WareOrderCars { get; set; }
    }
}
