//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderState
    {
        public OrderState()
        {
            this.WareOrderStates = new HashSet<WareOrderState>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string ColorCode { get; set; }
    
        public virtual ICollection<WareOrderState> WareOrderStates { get; set; }
    }
}
