//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityUser
    {
        public SecurityUser()
        {
            this.SecurityUserRoles = new HashSet<SecurityUserRole>();
            this.StaffEmployees = new HashSet<StaffEmployee>();
            this.WareDocuments = new HashSet<WareDocument>();
            this.WareOrderStates = new HashSet<WareOrderState>();
        }
    
        public int ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Login { get; set; }
        public string Hash { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<SecurityUserRole> SecurityUserRoles { get; set; }
        public virtual ICollection<StaffEmployee> StaffEmployees { get; set; }
        public virtual ICollection<WareDocument> WareDocuments { get; set; }
        public virtual ICollection<WareOrderState> WareOrderStates { get; set; }
    }
}
