//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffSheduler
    {
        public StaffSheduler()
        {
            this.StaffShedulerTeamEmployees = new HashSet<StaffShedulerTeamEmployee>();
        }
    
        public int ID { get; set; }
        public int DepartmentID { get; set; }
        public int ShiftID { get; set; }
        public int TeamID { get; set; }
        public Nullable<int> WorkPlaceID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public int CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual StaffDepartment StaffDepartment { get; set; }
        public virtual StaffEmployeeWorkPlace StaffEmployeeWorkPlace { get; set; }
        public virtual StaffShift StaffShift { get; set; }
        public virtual StaffTeam StaffTeam { get; set; }
        public virtual ICollection<StaffShedulerTeamEmployee> StaffShedulerTeamEmployees { get; set; }
    }
}
