//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffTeamEmployee
    {
        public int ID { get; set; }
        public int TeamID { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual StaffEmployee StaffEmployee { get; set; }
        public virtual StaffTeam StaffTeam { get; set; }
    }
}
