//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffTeam
    {
        public StaffTeam()
        {
            this.StaffShedulers = new HashSet<StaffSheduler>();
            this.StaffTeamEmployees = new HashSet<StaffTeamEmployee>();
            this.WareDocumentStaffDetails = new HashSet<WareDocumentStaffDetail>();
        }
    
        public int ID { get; set; }
        public int DepartmentID { get; set; }
        public string Name { get; set; }
    
        public virtual StaffDepartment StaffDepartment { get; set; }
        public virtual ICollection<StaffSheduler> StaffShedulers { get; set; }
        public virtual ICollection<StaffTeamEmployee> StaffTeamEmployees { get; set; }
        public virtual ICollection<WareDocumentStaffDetail> WareDocumentStaffDetails { get; set; }
    }
}
