//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffWorkPlace
    {
        public StaffWorkPlace()
        {
            this.StaffEmployeeWorkPlaces = new HashSet<StaffEmployeeWorkPlace>();
            this.WareDocuments = new HashSet<WareDocument>();
            this.WareOrders = new HashSet<WareOrder>();
        }
    
        public int ID { get; set; }
        public int Name { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    
        public virtual StaffDepartment StaffDepartment { get; set; }
        public virtual ICollection<StaffEmployeeWorkPlace> StaffEmployeeWorkPlaces { get; set; }
        public virtual ICollection<WareDocument> WareDocuments { get; set; }
        public virtual ICollection<WareOrder> WareOrders { get; set; }
    }
}
