//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDepartment
    {
        public StaffDepartment()
        {
            this.StaffDepartmentEmployees = new HashSet<StaffDepartmentEmployee>();
            this.StaffDepartments1 = new HashSet<StaffDepartment>();
            this.StaffSalaries = new HashSet<StaffSalary>();
            this.StaffShedulers = new HashSet<StaffSheduler>();
            this.StaffTeams = new HashSet<StaffTeam>();
            this.StaffWorkPlaces = new HashSet<StaffWorkPlace>();
            this.WareDepartments = new HashSet<WareDepartment>();
            this.WareDocuments = new HashSet<WareDocument>();
            this.WareDocuments1 = new HashSet<WareDocument>();
            this.WareOrders = new HashSet<WareOrder>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentDepartmentID { get; set; }
        public bool AllowServices { get; set; }
        public bool Active { get; set; }
        public int EnterpriseID { get; set; }
    
        public virtual Enterprise Enterprise { get; set; }
        public virtual ICollection<StaffDepartmentEmployee> StaffDepartmentEmployees { get; set; }
        public virtual ICollection<StaffDepartment> StaffDepartments1 { get; set; }
        public virtual StaffDepartment StaffDepartment1 { get; set; }
        public virtual ICollection<StaffSalary> StaffSalaries { get; set; }
        public virtual ICollection<StaffSheduler> StaffShedulers { get; set; }
        public virtual ICollection<StaffTeam> StaffTeams { get; set; }
        public virtual ICollection<StaffWorkPlace> StaffWorkPlaces { get; set; }
        public virtual ICollection<WareDepartment> WareDepartments { get; set; }
        public virtual ICollection<WareDocument> WareDocuments { get; set; }
        public virtual ICollection<WareDocument> WareDocuments1 { get; set; }
        public virtual ICollection<WareOrder> WareOrders { get; set; }
    }
}
