//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ware
    {
        public Ware()
        {
            this.WareCodes = new HashSet<WareCode>();
            this.WareComponentDetails = new HashSet<WareComponentDetail>();
            this.WareComponentRelations = new HashSet<WareComponentRelation>();
            this.WareDepartments = new HashSet<WareDepartment>();
            this.WareDocumentDetails = new HashSet<WareDocumentDetail>();
            this.WareOrderDetails = new HashSet<WareOrderDetail>();
            this.WarePrices = new HashSet<WarePrice>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public decimal Min { get; set; }
        public int UnitID { get; set; }
        public decimal UnitQuantity { get; set; }
        public Nullable<int> ManufactrerID { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual WareCategory WareCategory { get; set; }
        public virtual ICollection<WareCode> WareCodes { get; set; }
        public virtual ICollection<WareComponentDetail> WareComponentDetails { get; set; }
        public virtual ICollection<WareComponentRelation> WareComponentRelations { get; set; }
        public virtual ICollection<WareDepartment> WareDepartments { get; set; }
        public virtual ICollection<WareDocumentDetail> WareDocumentDetails { get; set; }
        public virtual WareManufacturer WareManufacturer { get; set; }
        public virtual ICollection<WareOrderDetail> WareOrderDetails { get; set; }
        public virtual ICollection<WarePrice> WarePrices { get; set; }
        public virtual WareUnit WareUnit { get; set; }
    }
}
