//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareOrder
    {
        public WareOrder()
        {
            this.WareDocuments = new HashSet<WareDocument>();
            this.WareOrderCars = new HashSet<WareOrderCar>();
            this.WareOrderDetails = new HashSet<WareOrderDetail>();
            this.WareOrderStates = new HashSet<WareOrderState>();
        }
    
        public int ID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> ContractorID { get; set; }
        public System.DateTime Date { get; set; }
        public string ContactName { get; set; }
        public string Description { get; set; }
        public string ContactPhone { get; set; }
        public bool Done { get; set; }
        public bool Canceled { get; set; }
        public int CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> DiscountID { get; set; }
        public decimal Price { get; set; }
        public int CurrencyID { get; set; }
        public int Duration { get; set; }
        public Nullable<int> WorkPlaceID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual StaffDepartment StaffDepartment { get; set; }
        public virtual StaffEmployee StaffEmployee { get; set; }
        public virtual StaffWorkPlace StaffWorkPlace { get; set; }
        public virtual ICollection<WareDocument> WareDocuments { get; set; }
        public virtual ICollection<WareOrderCar> WareOrderCars { get; set; }
        public virtual ICollection<WareOrderDetail> WareOrderDetails { get; set; }
        public virtual ICollection<WareOrderState> WareOrderStates { get; set; }
    }
}
