//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareDiscountRule
    {
        public int ID { get; set; }
        public int DiscountID { get; set; }
        public decimal StartSuma { get; set; }
        public Nullable<decimal> EndSuma { get; set; }
    
        public virtual WareDiscount WareDiscount { get; set; }
    }
}
