//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareCard
    {
        public WareCard()
        {
            this.ContractorCards = new HashSet<ContractorCard>();
            this.WareCardBalaces = new HashSet<WareCardBalace>();
            this.WareCardBalanceOperations = new HashSet<WareCardBalanceOperation>();
            this.WareCardCars = new HashSet<WareCardCar>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public int CardTypeID { get; set; }
        public int Active { get; set; }
        public Nullable<System.DateTime> IssuedDate { get; set; }
    
        public virtual ICollection<ContractorCard> ContractorCards { get; set; }
        public virtual ICollection<WareCardBalace> WareCardBalaces { get; set; }
        public virtual ICollection<WareCardBalanceOperation> WareCardBalanceOperations { get; set; }
        public virtual ICollection<WareCardCar> WareCardCars { get; set; }
        public virtual WareCardType WareCardType { get; set; }
    }
}
