//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareCategory
    {
        public WareCategory()
        {
            this.WareCategories1 = new HashSet<WareCategory>();
            this.Wares = new HashSet<Ware>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentCategoryID { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<WareCategory> WareCategories1 { get; set; }
        public virtual WareCategory WareCategory1 { get; set; }
        public virtual ICollection<Ware> Wares { get; set; }
    }
}
