//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarePrice
    {
        public int ID { get; set; }
        public int WareID { get; set; }
        public int WarePriceGroupID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public bool AllowDiscount { get; set; }
        public decimal PurchasePriceForUnit { get; set; }
        public decimal SalePriceForUnit { get; set; }
        public bool Active { get; set; }
    
        public virtual WareDocument WareDocument { get; set; }
        public virtual WarePriceGroup WarePriceGroup { get; set; }
        public virtual Ware Ware { get; set; }
    }
}
