//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarePriceGroup
    {
        public WarePriceGroup()
        {
            this.WarePriceGroups1 = new HashSet<WarePriceGroup>();
            this.WarePrices = new HashSet<WarePrice>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentGroupID { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<WarePriceGroup> WarePriceGroups1 { get; set; }
        public virtual WarePriceGroup WarePriceGroup1 { get; set; }
        public virtual ICollection<WarePrice> WarePrices { get; set; }
    }
}
