//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareCardCar
    {
        public int ID { get; set; }
        public int CardID { get; set; }
        public int CarID { get; set; }
    
        public virtual CWCar CWCar { get; set; }
        public virtual WareCard WareCard { get; set; }
    }
}
