//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareOrderDetail
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public int WareID { get; set; }
        public int UnitID { get; set; }
        public decimal UnitQuantity { get; set; }
        public decimal PriceForUnit { get; set; }
        public decimal Price { get; set; }
        public bool Active { get; set; }
        public string Description { get; set; }
    
        public virtual WareOrder WareOrder { get; set; }
        public virtual Ware Ware { get; set; }
        public virtual WareUnit WareUnit { get; set; }
    }
}
