//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareComponentDetail
    {
        public int ID { get; set; }
        public int WareID { get; set; }
        public int ComponentID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> UnitQuantity { get; set; }
        public Nullable<int> SecondUnitID { get; set; }
        public Nullable<decimal> SecondUnitQuantity { get; set; }
        public int Coefficient { get; set; }
    
        public virtual WareComponent WareComponent { get; set; }
        public virtual Ware Ware { get; set; }
        public virtual WareUnit WareUnit { get; set; }
        public virtual WareUnit WareUnit1 { get; set; }
    }
}
