//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareDocumentStaffDetail
    {
        public int ID { get; set; }
        public int DocumenDetailID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual StaffEmployee StaffEmployee { get; set; }
        public virtual StaffTeam StaffTeam { get; set; }
        public virtual WareDepartment WareDepartment { get; set; }
        public virtual WareDocumentDetail WareDocumentDetail { get; set; }
    }
}
