//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareCardTypeDiscount
    {
        public int ID { get; set; }
        public int CardTypeID { get; set; }
        public int DiscountID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual WareCardType WareCardType { get; set; }
        public virtual WareDiscount WareDiscount { get; set; }
    }
}
