//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareDiscount
    {
        public WareDiscount()
        {
            this.WareCardTypeDiscounts = new HashSet<WareCardTypeDiscount>();
            this.WareDiscountRules = new HashSet<WareDiscountRule>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DiscountTypeID { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<WareCardTypeDiscount> WareCardTypeDiscounts { get; set; }
        public virtual ICollection<WareDiscountRule> WareDiscountRules { get; set; }
        public virtual WareDiscountType WareDiscountType { get; set; }
    }
}
