//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareDocumentType
    {
        public WareDocumentType()
        {
            this.WareDocuments = new HashSet<WareDocument>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool Input { get; set; }
        public bool Output { get; set; }
    
        public virtual ICollection<WareDocument> WareDocuments { get; set; }
    }
}
