//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareUnit
    {
        public WareUnit()
        {
            this.WareComponentDetails = new HashSet<WareComponentDetail>();
            this.WareComponentDetails1 = new HashSet<WareComponentDetail>();
            this.WareDocumentDetails = new HashSet<WareDocumentDetail>();
            this.WareDocumentDetails1 = new HashSet<WareDocumentDetail>();
            this.WareOrderDetails = new HashSet<WareOrderDetail>();
            this.Wares = new HashSet<Ware>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<WareComponentDetail> WareComponentDetails { get; set; }
        public virtual ICollection<WareComponentDetail> WareComponentDetails1 { get; set; }
        public virtual ICollection<WareDocumentDetail> WareDocumentDetails { get; set; }
        public virtual ICollection<WareDocumentDetail> WareDocumentDetails1 { get; set; }
        public virtual ICollection<WareOrderDetail> WareOrderDetails { get; set; }
        public virtual ICollection<Ware> Wares { get; set; }
    }
}
