//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareDocument
    {
        public WareDocument()
        {
            this.WareDocumentDetails = new HashSet<WareDocumentDetail>();
            this.WarePrices = new HashSet<WarePrice>();
        }
    
        public int ID { get; set; }
        public string Number { get; set; }
        public int ContractorID { get; set; }
        public Nullable<int> ToDepartmentID { get; set; }
        public Nullable<int> FromDepartmentID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public decimal PurchaseSum { get; set; }
        public decimal PaySum { get; set; }
        public int DocumentTypeID { get; set; }
        public int CreatedUserID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int BaseID { get; set; }
        public Nullable<int> LinkedDocumentID { get; set; }
        public int WorkPlaceID { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Contractor Contractor { get; set; }
        public virtual SecurityUser SecurityUser { get; set; }
        public virtual StaffDepartment StaffDepartment { get; set; }
        public virtual StaffDepartment StaffDepartment1 { get; set; }
        public virtual StaffWorkPlace StaffWorkPlace { get; set; }
        public virtual WareBas WareBas { get; set; }
        public virtual ICollection<WareDocumentDetail> WareDocumentDetails { get; set; }
        public virtual WareDocumentType WareDocumentType { get; set; }
        public virtual WareOrder WareOrder { get; set; }
        public virtual ICollection<WarePrice> WarePrices { get; set; }
    }
}
