//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareDocumentDetail
    {
        public WareDocumentDetail()
        {
            this.WareDocumentStaffDetails = new HashSet<WareDocumentStaffDetail>();
        }
    
        public int ID { get; set; }
        public int DocumentID { get; set; }
        public int WareID { get; set; }
        public int UnitID { get; set; }
        public decimal UnitQuantity { get; set; }
        public Nullable<int> SecondUnitID { get; set; }
        public Nullable<decimal> SecondUnitQuantity { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<decimal> PurchasePriceForUnit { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
        public Nullable<decimal> SalePriceForUnit { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public int CurrencyID { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual WareDocument WareDocument { get; set; }
        public virtual Ware Ware { get; set; }
        public virtual WareUnit WareUnit { get; set; }
        public virtual WareUnit WareUnit1 { get; set; }
        public virtual ICollection<WareDocumentStaffDetail> WareDocumentStaffDetails { get; set; }
    }
}
