//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compas.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareCardType
    {
        public WareCardType()
        {
            this.WareCards = new HashSet<WareCard>();
            this.WareCardTypeDiscounts = new HashSet<WareCardTypeDiscount>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool AllowBalance { get; set; }
        public Nullable<bool> AllowMultipleCars { get; set; }
    
        public virtual ICollection<WareCard> WareCards { get; set; }
        public virtual ICollection<WareCardTypeDiscount> WareCardTypeDiscounts { get; set; }
    }
}
